version: '3.7'

services:
  reservation:
    build: ./
    depends_on:
      - 'database'
    ports: 
      - '3000:3000'

  database:
    image: mysql:5.7.28
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=sheep
      - MYSQL_ROOT_HOST=%
    volumes:
      - type: volume
        source: my_sql_data
        target: /var/lib/mysql

volumes:
  my_sql_data: 
    external: true
